version: "3.8"
# network in which container live
networks:
  cyckelwebb:
# services for the application
services:
  # backend server
  server:
    image: node:20
    container_name: "server"
    ports:
      - "1338:1338"
    volumes:
      - "./backend:/server"
      - "./db:/db"
    working_dir: /server
    # How to start the server
    # Alternatively create another service (see below)
    command: bash -c "npm install && npm run start"
    networks:
      - cyckelwebb
    # container is always restarted if it stops
    restart: "always"

  # start server in dev mode (with nodemon)
  dev-server:
    image: node:20
    container_name: "server"
    ports:
      - "1338:1338"
    volumes:
      - "./backend:/server"
      - "./db:/db"
    working_dir: /server
    command:  bash -c "npm install && npm run start-dev"
    networks:
      - cyckelwebb
    restart: "always"

  # A database will be created from db/sql/setup.sql
  # create db with: docker compose up sqlite-db
  sqlite-db:
    image: "eeemiiil/sqlite:1"
    container_name: "database"
    volumes:
      - "./db:/db"
    working_dir: /db
    command: bash -c "./setup.db.bash"

  # frontend app
  webapp:
    image: node:20
    container_name: "webapp"
    restart: unless-stopped
    expose:
      - 5173
    ports:
      - "5173:5173"
    volumes:
      - "./frontend:/webapp"
    working_dir: /webapp
    command:  bash -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - cyckelwebb
    environment:
      - NODE_ENV=development
    # linking the server and app is not needed
    # if these services run within the same network
    # links:
    #   - "server:server"
