version: "3.8"
# network in which container live
networks:
  cyckelwebb:
# services for the application
services:
  # backend server
  server:
    image: node:latest
    container_name: "server"
    ports:
      - "1338:1338"
    volumes:
      - "./backend:/server"
    working_dir: /server
    # How to start the server
    # Alternatively create another service (see below)
    command: bash -c "npm install && npm run start"
    networks:
      - cyckelwebb
    # container is always restarted if it stops
    restart: "always"

  # start server in dev mode (with nodemon)
  dev-server:
    image: node:latest
    container_name: "server"
    ports:
      - "1338:1338"
    volumes:
      - "./backend:/server"
    working_dir: /server
    command:  bash -c "npm install && npm run start-dev"
    networks:
      - cyckelwebb
    restart: "always"

  # frontend app
  # webapp:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   networks:
  #     cyckelwebb:
  #   links:
  #     - "server:server"
